### ISSUE TITLE
Artwork 

### ISSUE THREAD

**Issue by loaykhalifa** [kirtan-shah/nowplaying-cli#24]
how to extract artwork as jpeg ?
Mac OS Sonoma 14.5

**Comment by kirtan-shah** [comment]
`nowplaying-cli get artworkData ` gives you a base64 encoded image.
One potential example to get a jpeg (not endorsing ffmpeg in particular): 
`nowplaying-cli get artworkData | base64 --decode | ffmpeg -i pipe:0 out.jpg`

Basically you're doing base64 -> bmp -> jpg
