### ISSUE TITLE
Is it possible to use this to render the album artwork using nowplaying-cli?

### ISSUE THREAD

**Issue by pogmommy** [kirtan-shah/nowplaying-cli#4]
I'm trying to use this to get now-playing information into an ubersicht widget. Is there a way to get kMRMediaRemoteNowPlayingInfoArtworkData in a more readable format? Unless I'm unfamiliar with the format used, it seems like the data made available is abbreviated and isn't able to be used for rendering the album artwork.

No worries if not, thank you for the time and effort put into this, it's wildly useful even if this use-case isn't within the scope of this project!

**Comment by kirtan-shah** [comment]
I believe this can be done. We just need to add a special case for artworkData that will print out the unabbreviated data.

I'm debating whether it would be better to output the data in binary format (to be piped or redirected to a file), or in some ASCII format (hex, base64?)

**Comment by kirtan-shah** [comment]
I decided to output the data in base64 format because you can pipe into `base64 -decode` on a mac if you need the binary format. The latest release now supports getting the full album artwork!

**Comment by frypf** [comment]
I have one machine running Monterey and one on Ventura, but only the Ventura one returns anything for `artworkData` - just wanted to check is this intended/expected behaviour?
Thanks for this very useful little tool!
