### ISSUE TITLE
Possible to do this using non-private APIs?

### ISSUE THREAD

**Issue by RSully** [kirtan-shah/nowplaying-cli#5]
Is it possible to leverage the Media Player framework to return this data without using private APIs? I saw this API reference, but haven't had time to dig into it too much: https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter/1615903-nowplayinginfo

**Comment by kirtan-shah** [comment]
I experimented with that and I believe that is meant for apps to report what media they are playing, and is therefore write-only.
