### ISSUE TITLE
elapsedTime does not update until media is paused and unpaused.

### ISSUE THREAD

**Issue by pogmommy** [kirtan-shah/nowplaying-cli#6]
The terminal output below is the result of running `nowplaying-cli get elapsedTime` every 5-10 of seconds. The elapsedTime seems to get stuck where the media playback state last changed. The media was paused and unpaused between the third and fourth command below, which is where the elapsed time updates and then remains stuck at the new value.

```
~ % nowplaying-cli get elapsedTime
191.8892669677734
~ % nowplaying-cli get elapsedTime
191.8892669677734
~ % nowplaying-cli get elapsedTime
191.8892669677734
~ % nowplaying-cli get elapsedTime
242.7073516845703
~ % nowplaying-cli get elapsedTime
242.7073516845703
~ % nowplaying-cli get elapsedTime
242.7073516845703
```

**Comment by kirtan-shah** [comment]
Interesting, I'm getting updates when played/paused as you are, and also sometimes randomly (rarely) in 1.5 sec / 3 sec increments. My best guess is this is a value updated by Spotify (or whatever media app is playing).

**Comment by nyxaria** [comment]
Hi was this fixed? It seems to still be happening to me with both youtube and spotify
